import streamlit as st
st.header(':rainbow[Em yeu hoa hoc]')
def pt(promp):
    x = promp.split()
    if len(x) != 0:
        x[x.index('=')] = '->'
        s = [j for j in x if j != '+' and j != '->']
        d = []
        for u in s:
            for i in range(len(u)):
                if u[i].isupper() and u[i] not in d:
                    d.append(u[i])
                if u[i].islower():
                    if u[i-1:i+1] not in d:
                        d[d.index(u[i-1])] = u[i-1:i+1]
                    else:
                        d.remove(u[i-1])
        st.latex(' '.join(x))
        return(d)
def nt(d):
    f = {
        'H' : ['Hydrogen(H)','Một nguyên tử hydro là một nguyên tử của nguyên tố hóa học hydro. Nguyên tử điện tích trung lập, chỉ chứa duy nhất một hạt proton mang điện tích dương và một hạt electron mang điện tích âm, bị ràng buộc với hạt nhân bởi lực Coulomb. Nguyên tử hydro cấu thành khoảng 75% khối lượng baryon của vũ trụ.'],
        'He' : ['Helium(He)', 'Heli là nguyên tố nhiều thứ hai trong vũ trụ sau hydro. Trong khí quyển Trái Đất, mật độ heli theo thể tích là 5,2 x 10−6 tại mực nước biển và tăng dần đến độ cao 24 km, chủ yếu là do phần lớn heli trong bầu khí quyển Trái Đất đã thoát ra ngoài khoảng không gian vũ trụ vì tỷ trọng thấp và tính trơ của nó. Có một lớp trong bầu khí quyển Trái Đất ở độ cao khoảng 1.000 km mà ở đó heli là chất khí chủ yếu (mặc dù tổng áp suất gây ra là rất nhỏ)'],
        'Li' : ['Lithium(Li)','Lithi hay liti[4] là một nguyên tố hóa học trong bảng tuần hoàn nguyên tố có ký hiệu Li[5] và số hiệu nguyên tử bằng 3, nguyên tử khối bằng 7. Lithi là một kim loại mềm có màu trắng bạc thuộc nhóm kim loại kiềm. Trong điều kiện tiêu chuẩn, Lithi là kim loại nhẹ nhất và là nguyên tố rắn có mật độ thấp nhất. Giống như tất cả các kim loại kiềm, Lithi là chất phản ứng mạnh và dễ cháy khi tiếp xúc với nước nên nó được bảo quản đặc biệt trong dầu khoáng. Lithi có ánh kim loại nhưng khi tiếp xúc với không khí ẩm nó bị ăn mòn bề mặt và bị chuyển màu nhanh chóng thành xám bạc mờ, sau đó là xỉn đen. Do có khả năng phản ứng mạnh, Lithi không bao giờ có mặt ở dạng nguyên tố trong tự nhiên, do vậy nó chỉ có ở dạng hợp chất ở dạng liên kết ion. Lithi có mặt nhiều trong các khoáng sản pegmatit, nhưng do tính dễ hòa tan ở dạng ion, nó cũng có mặt trong nước biển, và thường được tách ra từ muối và đất sét. Ở quy mô thương mại, lithi được tách ra bằng phương pháp điện phân từ hỗn hợp của lithi chloride và kali chloride.'],
        'Be' : ['Beryllium(Be)','Beryli, berili hay thường được gọi ngắn là beri là một nguyên tố hóa học trong bảng tuần hoàn có ký hiệu Be và số nguyên tử bằng 4, nguyên tử khối bằng 9. Là một nguyên tố hóa trị hai có độc tính, beryli có màu xám như thép, cứng, nhẹ và giòn, và là kim loại kiềm thổ, được sử dụng chủ yếu như chất làm cứng trong các hợp kim.'],
        'B' : ['Boron(B)','Bor (bắt nguồn từ từ tiếng Pháp bore /bɔʁ/)[6] là một nguyên tố hóa học trong bảng tuần hoàn nguyên tố có ký hiệu B và số hiệu nguyên tử bằng 5, nguyên tử khối bằng 11.'],
        'C' : ['Carbon(C)','Carbon hay Cacbon (bắt nguồn từ tiếng Pháp carbone (/kaʁbɔn/)),[9] là nguyên tố hóa học trong bảng tuần hoàn có ký hiệu là C và số nguyên tử bằng 6, nguyên tử khối bằng 12. Là một nguyên tố phi kim có hóa trị 4 phổ biến, carbon có nhiều dạng thù hình khác nhau, phổ biến nhất là 4 dạng thù hình gồm carbon vô định hình, graphit, kim cương và Q-carbon.'],
        'N' : ['Nitrogen(N)','Nitơ (danh pháp IUPAC: nitrogen) là một nguyên tố hóa học trong bảng tuần hoàn các nguyên tố có ký hiệu N và số nguyên tử bằng 7, nguyên tử khối bằng 14. Ở điều kiện bình thường nó là một chất khí không màu, không mùi, không vị và khá trơ và tồn tại dưới dạng phân tử N2, còn gọi là đạm khí. Nitơ chiếm khoảng 78% khí quyển Trái Đất và là thành phần của mọi cơ thể sống. Nitơ tạo ra nhiều hợp chất quan trọng như các amino acid, amonia, acid nitric và các cyanide. Liên kết hóa học cực kỳ bền vững giữa các nguyên tử nitơ gây khó khăn cho cả sinh vật và công nghiệp để chuyển hóa N. 2 thành các hợp chất hóa học hữu dụng, nhưng đồng thời cũng giải phóng một lượng lớn năng lượng hữu ích khi cháy, nổ hoặc phân hủy trở lại thành khí nitơ. Các ammoniac và nitrat được tổng hợp là các loại phân công nghiệp chính và phân nitrat là các chất ô nhiễm chính gây ra hiện tượng phú dưỡng môi trường nước.'],
        'O' : ['Oxygen(O)','Oxy (tiếng Anh: oxygen /ˈɒksɪdʒən/; bắt nguồn từ từ tiếng Pháp oxygène [ɔsiʒɛn][4]), hay dưỡng khí, là một nguyên tố hóa học có ký hiệu O và số hiệu nguyên tử 8. Nó là một thành viên của nhóm chalcogen trong bảng tuần hoàn, một phi kim phản ứng mạnh và là một chất oxy hóa dễ tạo oxide với hầu hết các nguyên tố cũng như với các hợp chất khác. Sau hydro và heli, oxy là nguyên tố phong phú thứ ba trong vũ trụ tính theo khối lượng.'],
        'F' : ['Fluorine(F)','Fluor (danh pháp cũ: flo) là một nguyên tố hóa học có ký hiệu là F và số hiệu nguyên tử là 9. Đây là halogen nhẹ nhất và tồn tại dưới dạng chất khí rất độc, màu vàng nhạt ở điều kiện tiêu chuẩn. Do có độ âm điện cao nhất, fluor hoạt động hóa học rất mạnh: phản ứng với hầu hết nguyên tố khác, bao gồm một số khí hiếm, để tạo thành hợp chất với fluor.'],
        'Ne' : ['Neon(Ne)','Neon là nguyên tố hóa học trong bảng tuần hoàn nguyên tố có ký hiệu Ne và số nguyên tử bằng 10, nguyên tử khối bằng 20. Là một khí hiếm không màu, gần như trơ, neon tạo ra ánh sáng màu đỏ khi sử dụng trong các ống phóng điện chân không và đèn neon, nó có trong không khí với một lượng rất nhỏ.'],
        'Na' : ['Sodium(Na)','Natri (bắt nguồn từ tiếng Tân Latinh: natrium; danh pháp IUPAC: sodium; ký hiệu hóa học: Na) là một nguyên tố hóa học thuộc nhóm kim loại kiềm có hóa trị một trong bảng tuần hoàn nguyên tố với số nguyên tử bằng 11 và nguyên tử khối bằng 23. Đây là một kim loại mềm, màu trắng bạc và hoạt động mạnh; natri chỉ có một đồng vị bền là 23Na. Kim loại natri nguyên chất không tồn tại trong tự nhiên, do đó con người phải điều chế natri kim loại từ các hợp chất của natri. Natri là nguyên tố phổ biến thứ 6 trong vỏ Trái Đất và có mặt trong nhiều loại khoáng vật như felspat, sodalit và đá muối (NaCl). Phần lớn muối natri là những hợp chất hòa tan tốt trong nước: các ion natri trong các hợp chất đó bị rò rỉ do hoạt động của nước nên chlor và natri là các nguyên tố hòa tan phổ biến nhất theo khối lượng trong các vùng biển trên Trái Đất.'],
        'Mg' : ['Magnesium(Mg)','Magnesium là một nguyên tố hóa học; nó có ký hiệu Mg và số nguyên tử 12. Nó là kim loại màu xám sáng bóng có mật độ thấp, điểm nóng chảy thấp và khả năng phản ứng hóa học cao. Giống như các kim loại kiềm thổ khác (nhóm 2 của bảng tuần hoàn), nó chỉ xuất hiện trong tự nhiên khi kết hợp với các nguyên tố khác và hầu như luôn có trạng thái oxy hóa +2. Nó phản ứng dễ dàng với không khí để tạo thành một lớp phủ thụ động mỏng magie oxit có tác dụng ức chế sự ăn mòn thêm của kim loại. Kim loại tự do cháy với ánh sáng trắng rực rỡ. Kim loại này thu được chủ yếu bằng cách điện phân muối magie thu được từ nước muối. Nó ít đậm đặc hơn nhôm và được sử dụng chủ yếu như một thành phần trong các hợp kim bền và nhẹ có chứa nhôm.'],
        'Al' : ['Aluminium(Al)','Nhôm là một nguyên tố hóa học có ký hiệu Al và số nguyên tử 13. Nhôm có khối lượng riêng thấp hơn các kim loại thông thường khác, khoảng một phần ba so với thép. Nhôm có ái lực cao với oxy, từ đó tạo thành một lớp oxide bảo vệ trên bề mặt khi tiếp xúc với không khí. Nhôm có màu giống bạc và có khả năng phản xạ ánh sáng rất tốt. Nhôm là kim loại mềm, dẻo và không có từ tính. Nhôm có một đồng vị ổn định, 27 Al; đồng vị này rất phổ biến nên nhôm là nguyên tố phổ biến thứ 12 trong vũ trụ. Tính phóng xạ cao của đồng vị kém bền 26 Al khiến nó được áp dụng trong phương pháp xác định niên đại bằng đồng vị phóng xạ.'],
        'Si' : ['Silicon(Si)','Silic (Tiếng Anh: silicon) là một nguyên tố hóa học trong bảng tuần hoàn nguyên tố có ký hiệu Si và số nguyên tử bằng 14. Nó là nguyên tố phổ biến sau oxy trong vỏ Trái Đất (25,8 %), cứng, có màu xám sẫm - ánh xanh kim loại, là á kim có hóa trị +4.'],
        'P' : ['Phosphorus(P)','Phosphorus hay phốt pho theo phiên âm tiếng Việt[4] (từ tiếng Hy Lạp: phôs có nghĩa là "ánh sáng" và phoros nghĩa là "người/vật mang"), là một nguyên tố hóa học trong bảng tuần hoàn có ký hiệu P và số nguyên tử 15. Là một phi kim đa hóa trị trong nhóm nitơ,phosphorus chủ yếu được tìm thấy trong các loại đá phosphat vô cơ và trong các cơ thể sống. Do độ hoạt động hóa học cao, không bao giờ người ta tìm thấy nó ở dạng đơn chất trong tự nhiên. Nó phát xạ ra ánh sáng nhạt khi bị phơi ra trước oxy (vì thế có tên gọi của nó trong tiếng Latinh để chỉ "ngôi sao buổi sáng", từ tiếng Hy Lạp có nghĩa là "ánh sáng" và "mang"), và xuất hiện dưới một số dạng thù hình. Nó cũng là nguyên tố thiết yếu cho các cơ thể sống. Sử dụng quan trọng nhất trong thương mại của nó là để sản xuất phân bón. Nó cũng được sử dụng rộng rãi trong các loại vật liệu nổ, diêm, pháo hoa, thuốc trừ sâu, kem đánh răng và chất tẩy rửa.'],
        'S' : ['Sulfur(S)', 'Lưu huỳnh (tên khác: Sulfur (đọc như "Xun-phu"), lưu hoàng hay diêm sinh) là nguyên tố hóa học trong bảng tuần hoàn có ký hiệu S và số nguyên tử 16. Nó là một phi kim phổ biến, không mùi, không vị, nhiều hóa trị. Lưu huỳnh, trong dạng gốc của nó là chất rắn kết tinh màu vàng chanh. Trong tự nhiên, nó có thể tìm thấy ở dạng đơn chất hay trong các khoáng chất sulfide và sulfat. Nó là một nguyên tố thiết yếu cho sự sống và được tìm thấy trong hai amino acid. Lưu huỳnh được ứng dụng chủ yếu để tạo ra axit sunfuric-nguyên liệu sản xuất phân lân (P) nhưng cũng được dùng rộng rãi trong việc chế tạo thuốc súng, diêm, thuốc trừ sâu và thuốc diệt nấm.'],
        'Cl' : ['Chlorine(Cl)','Chlor (hay clo, danh pháp IUPAC là chlorine) là nguyên tố hóa học trong bảng tuần hoàn nguyên tố có ký hiệu Cl và số nguyên tử bằng 17, thường tồn tại ở phân tử dạng 2 nguyên tử (Cl2). Nguyên tố này là một halogen, nằm ở ô số 17, thuộc chu kì 3 của bảng tuần hoàn. Ion chlor là một thành phần của muối ăn và các hợp chất khác, nó phổ biến trong tự nhiên và chất cần thiết để tạo ra phần lớn các loại hình sự sống, bao gồm cả cơ thể người. Chlor có ái lực điện tử cao nhất và có độ âm điện đứng thứ 3 trong tất cả các nguyên tố.'],
        'Ar' : ['Argon(Ar)','Argon là một nguyên tố hóa học trong bảng tuần hoàn. Nó có ký hiệu Ar và số nguyên tử bằng 18. Là khí hiếm thứ ba trong nhóm 8, argon chiếm khoảng 0,934% khí quyển Trái Đất, điều này làm cho nó trở thành khí hiếm phổ biến nhất trên Trái Đất.'],
        'K' : ['Potassium(K)','Kali (bắt nguồn từ tiếng Tân Latinh: kalium, danh pháp IUPAC: potassium) là nguyên tố hoá học ký hiệu K, số thứ tự 19 trong bảng tuần hoàn. Ngoài những tên đã nêu, Kali còn được gọi là bồ tạt (nhiều khi được dùng để chỉ kali carbonat K2CO3) hay potassium. Kali nguyên tố là kim loại kiềm mềm, có màu trắng bạc dễ bị oxy hóa trong không khí và phản ứng rất mạnh với nước tạo ra một lượng nhiệt đủ để đốt cháy lượng hydro sinh ra từ phản ứng đã nêu. Kali khi cháy có ngọn lửa màu hoa cà.'],
        'Ca' : ['Calcium(Ca)','Calci, hay còn được viết là canxi,[5] là một nguyên tố hóa học có ký hiệu Ca và số nguyên tử 20. Là một kim loại kiềm thổ, calci có độ phản ứng cao: nó tạo thành một lớp oxide-nitride màu trắng xám khi tiếp xúc với không khí. Các tính chất vật lý và hóa học của nó gần giống với các chất tương đồng nặng hơn như là stronti và bari. Nó là nguyên tố phổ biến thứ năm trên vỏ Trái Đất, và là kim loại phổ biến thứ ba chỉ sau sắt và nhôm. Hợp chất calci phổ biến nhất trên Trái Đất là calci carbonat, có trong đá vôi và tàn tích hóa thạch của sinh vật biển trong thời kỳ đầu; nguồn calci khác bao gồm thạch cao,'],
       }
    if len(d)!= 0:
        with st.container(border = True):
            for t in d:
                st.header(f[t][0])
                st.write(f[t][1])

def main():
    d = pt(st.text_input('Nhap phuong trinh hoa hoc'))
    nt(d)
main()
